### ISSUE TITLE
png quality has weird behaviour

### ISSUE THREAD

**Issue by gsouf** [claviska/SimpleImage#115]
https://github.com/claviska/SimpleImage/blob/2.6.0/src/abeautifulsite/SimpleImage.php#L645

According this line the max quality is 9 (on a scale of 0-100 for the parameter). If I want to update the quality I'm going make it explicitly or to use some pngquant. 

Is it done on the purpose ? If yes, why ?

**Comment by claviska** [comment]
PNG is lossless and therefore doesn't technically have a quality level like JPEG. However, the `imagepng()` function does accept a `$quality` argument, but it's used for compression instead of image quality. [Per the docs](http://php.net/manual/en/function.imagepng.php), acceptable values for this argument are 0-9.

My guess is that the PHP manual uses the term `$quality` instead of something like `$compression` to be consistent with the `imagejpeg()` function.

So why not use 9 all the time for PNGs if the quality will be the same? Because higher compression requires more time, and if you're running batch processes it can become very expensive :)

Thus, the SimpleImage library accepts quality as a 0-100 percentage to normalize the "quality" argument that `imagepng()` (0-9) and `imagejpeg()` (0-100) both use. This lets you set a relatively similar quality without having to be conscious of the image's format.

**Comment by gsouf** [comment]
Makes sense :+1:
