### ISSUE TITLE
"Unsupported format" after uploading image

### ISSUE THREAD

**Issue by mrhmansour** [claviska/SimpleImage#125]
When i used image after aploading , i have the error "unsupported format" !!

**Comment by SmetDenis** [comment]
Hi,

I think the problem is same like here
https://github.com/JBZoo/Image/issues/1#issuecomment-183346002

When you upload file, it has ext ".tmp"
SimpleImage try to find gif, jpeg/jpg or png
https://github.com/claviska/SimpleImage/blob/master/src/abeautifulsite/SimpleImage.php#L891

I decided that via mime (in my fork)
https://github.com/JBZoo/Image/blob/master/src/Image.php#L272

Best regards, Denis.
