### ISSUE TITLE
Rotating image twice

### ISSUE THREAD

**Issue by penafo** [claviska/SimpleImage#131]
Detected some weird problems when rotating an image twice (90º + 90º) and saving specifically stating quality 100.

The generated image:
- has a lot less quality (blurry);
- filesize more than TRIPLES (56kb > 172kb)!!
- width gets reduced in 1 pixel
- height gets reduced in 1 pixel
- gets added a 1 pixel black left border
- gets added a 1 pixel black bottom border

Related Images:
http://afonsogomes.com/SimpleImage-ex-original.jpg
http://afonsogomes.com/SimpleImage-ex-generated.jpg

**Comment by claviska** [comment]
Keep in mind SimpleImage uses the GD library for most operations :)

So, for example, the [`rotate()`](https://github.com/claviska/SimpleImage/blob/master/src/abeautifulsite/SimpleImage.php#L850) methods uses [`imagerotate()`](http://php.net/manual/en/function.imagerotate.php) to perform the actual rotation. The method is very basic, and I don't see anything that might cause this so I'm betting the same operation using only GD (i.e. without SimpleImage) will yield the same result.

To address your issues:

> has a lot less quality (blurry);

This depends on the operations you do and the quality you save. If you keep resaving an image as a lossy JPEG, there will be more and more quality loss after each operation.

So it's better to do one rotation as 180 instead of two at 90. If your app requires this (e.g. to allow users to hit a button multiple times to rotate to the desired orientation), then you'll want to maintain an original image and use as the source each time.

> filesize more than TRIPLES (56kb > 172kb)!!

When saving a JPEG at 100 quality, it's going to be huge even if the original is smaller. It's the least lossy quality that JPEG offers. 80 is a good balance of size/quality and is also the default.

This isn't limited to SimpleImage. Create a large image in Photoshop and fill it with a photo or a gradient. Save it as a 20% JPEG. Then close it and reopen it. Now save it as a 100% JPEG. The new image will be much larger despite its quality.

> width gets reduced in 1 pixel
> height gets reduced in 1 pixel
> gets added a 1 pixel black left border
> gets added a 1 pixel black bottom border

Without seeing any code, I suspect this is happening in the `imagerotate()` function and the black border is probably a result of a rounding error. Make sure you're passing an integer value.
