### ISSUE TITLE
Error load Image URL fromFile

### ISSUE THREAD

**Issue by nikmauro** [claviska/SimpleImage#162]
The file exist in function fromFile dont work with  Relative URL if comment the condition file_exists working perfect.
```
/*
    if(!file_exists($file)) {
      throw new \Exception("File not found: $file", self::ERR_FILE_NOT_FOUND);
    }
*/
```

**Comment by claviska** [comment]
Relative paths or URLs? Can you post an example?

**Comment by nikmauro** [comment]
```PHP
$file="https://s-media-cache-ak0.pinimg.com/originals/cf/28/85/cf28858a4c2c511dba8bcd04980cff5a.jpg";
$img = new \claviska\SimpleImage($file);

Fatal error: Uncaught Exception: File not found: https://s-media-cache-ak0.pinimg.com/originals/cf/28/85/cf28858a4c2c511dba8bcd04980cff5a.jpg in /vendor/abeautifulsite/simpleimage/src/claviska/SimpleImage.php:116 Stack trace: #0 /vendor/abeautifulsite/simpleimage/src/claviska/SimpleImage.php(57): claviska\SimpleImage->fromFile('https://s-media...') #1 /library/cms39_media.php(636): claviska\SimpleImage->__construct('http://www2.dom...') #2 /library/cms39_media.php(121): resizePhoto(Array) #3 /public/themes/shop/functions.php(246): processImage('2016/11/g3140-1...', Array) #4 /public/plugins/cms39_blog/cms39_blog.plugin.php(205): theme_data('467', Array) #5 /public/themes/shop/functions.php(334): BlogPosts('shopping', Array) #6 / in /vendor/abeautifulsite/simpleimage/src/claviska/SimpleImage.php on line 116

```

**Comment by nikmauro** [comment]
I think the  file_exist statement is  better to used by user and not from library.

**Comment by claviska** [comment]
The problem is that some URL wrappers don't support `stat()` and therefore `file_exists()`, so it fails for those wrappers.

Simply removing the check _does_ make it work when the resource exists and is a valid image. If not, the proceeding call to `getimagesize()` will fail and generate a nasty warning.

I submitted a patch that uses `fopen()` to test for readability (and thus existence) that will work with all wrappers, including the local filesystem.

**Developer note:** I'm suppressing the potential `fopen()` warning with `@` per the [manual](http://php.net/manual/en/function.fopen.php). I prefer not using `@`, but the function doesn't provide a way to opt out of the warning and `set_error_handler()` is too verbose for particular application.
