### ISSUE TITLE
Does it work on PHP 5.3, 5.4 and 5.5?

### ISSUE THREAD

**Issue by GazCBG** [claviska/SimpleImage#175]
Hi,

I know it says PHP 5.6+, but does it work on PHP 5.3, 5.4 and 5.5?
Please let me know.

Thanks

**Comment by claviska** [comment]
No, because the code uses features that require that version. One that immediately comes to mind is array shorthands, which require PHP 5.4.

You might have luck with that version, but I'd strongly advise against using any end-of-lifed software. As of know, [only 5.6 and up](http://php.net/supported-versions.php) is still maintained. You should talk to your web host about upgrading ASAP.
