### ISSUE TITLE
Empty $quality param

### ISSUE THREAD

**Issue by bloxcms** [claviska/SimpleImage#183]
The method toFile(..., ..., $quality) treats empty $quality param ambiguously:
$quality='' as 100
$quality=null as 0
Apparently "null" should be considered as default , i.e. 100

**Comment by claviska** [comment]
The `$quality` argument should always be an integer or null. However, due to the way it was being passed to `keepWithin()` in the `generate()` method, null values were incorrectly resulting in `null` instead of an integer.

With 3158283, null values will correctly resolve to the default of `100`. Keep in mind that `''` is an empty string and will (correctly) resolve to `0`.

To ensure you always get the quality you desire, make sure you pass an integer value.
