### ISSUE TITLE
v3.3.1 thumbnail makes png background black

### ISSUE THREAD

**Issue by Graziel** [claviska/SimpleImage#188]
<pre>
public function transform()
    {
        $this->settings += [
            'thumbnails' => []
        ];

        $extension = pathinfo($this->data['name'], PATHINFO_EXTENSION);
        $base = pathinfo($this->data['name'], PATHINFO_FILENAME);

        if (!is_dir(ROOT . DS . $this->basepath())) {
            mkdir(ROOT . DS . $this->basepath(), 0777, true);
        }

        $scaler = new SimpleImage();

        $scaler->fromFile($this->data['tmp_name'])
            ->bestFit($this->settings['fitToWidth'], $this->settings['fitToHeight'])
            ->toFile(ROOT . DS . $this->basepath() . $this->data['name']);

        foreach ($this->settings['thumbnails'] as $thumbnail) {
            $width = $thumbnail['width'];
            $height = $thumbnail['height'];
            $outputFile = ROOT . DS . $this->basepath() . $base . '_' . $width . 'x' . $height . '.' . $extension;

            $scaler = new SimpleImage();
            $scaler->fromFile($this->data['tmp_name'])
                ->thumbnail($width, $height)
                ->toFile($outputFile);
        }

        return [];
    }
</pre>
creates best fit and thumbnails for me, while best fit saves transparency, thumbnail makes background black

![36b6c1e1-77de-41b3-a14b-bc2f35322028](https://cloud.githubusercontent.com/assets/5963584/26778770/f8fe22f8-49e2-11e7-8e6c-72bd59915ba4.png)
![36b6c1e1-77de-41b3-a14b-bc2f35322028_115x75](https://cloud.githubusercontent.com/assets/5963584/26778778/febf840c-49e2-11e7-95e3-1d4be4e8d8d7.png)

**Comment by claviska** [comment]
Please try to post a minimal test case in the future. It wasn't clear what you were trying to convey, and even with all that code I can't replicate exactly what you're seeing. (What dimensions did you use, for example? )

I gather you took this image:

![original](https://cloud.githubusercontent.com/assets/55639/26789296/d7b906bc-49dd-11e7-95f6-d349c0dab0c8.png)

And ran it through the `bestFit` and `thumbnail` methods on two separate passes. For `bestFit`, everything worked as expected. For `thumbnail`, you received the image with a black background.

Here's the code I used to test `bestFit`:

```php
$image
  ->fromFile('test.png')
  ->bestFit(100, 100)
  ->toScreen();
```

Result:

![best-fit](https://cloud.githubusercontent.com/assets/55639/26789302/e3c1dec0-49dd-11e7-8c14-b7c0ca4746ea.png)

Here's the code I used to test `thumbnail`:

```php
$image
  ->fromFile('test.png')
  ->thumbnail(100, 100)
  ->toScreen();
```

Result:

![thumbnail](https://cloud.githubusercontent.com/assets/55639/26789333/044075e4-49de-11e7-9659-de2e29083554.png)

Everything looks as it's expected to look. I even tried some other dimensions just to test and they rendered correctly too.

If you can reproduce this with a minimal test case, I'll be happy to reopen. Otherwise, my best guess is there's something else in your code causing this to happen.

**Comment by Graziel** [comment]
what you posted is basically what my test case is - dimensions doesn't matter, ive tracked my issue to `imagecrop` function, if i rewrite it to use `imagecopyresampled` it works as expected so its probably something related to GD/libpng versions
