### ISSUE TITLE
Create a gallery thumb on the fly

### ISSUE THREAD

**Issue by mike0liveira** [claviska/SimpleImage#209]
All right folks, im tring to do something like this: 

```
for ($i=0;$i<10;$i++){
   $path = $i."img.jpg";
   $origImage = new \claviska\SimpleImage($path);
   $origImage->thumbnail(200, 200, "center");
   $origImage->toScreen();
}
```

but just don't work, can any one help me, it is possible?

**Comment by claviska** [comment]
You can’t out put multiple images to the screen like that. Use the toFile
method and then display them as normal HTML images with src.

**Comment by mike0liveira** [comment]
But I do not want to create a new file, the toFile method is great when we upload an image. It is not possible to create a thumb in real time? So what is the toScreen method, just for testing?

**Comment by claviska** [comment]
The `toScreen()` method [sets the content type](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L343-L344) so it can't be used inside a webpage. It's useful for when you need to generate an image resource dynamically.

There are a couple ways you can achieve what you're trying to do:

1. You can use a script to generate each image on the fly, but the script needs to be the `src` of the image. For example:

```html
<img src="script.php?yourParams=123">
```

However, I wouldn't recommend this for well-trafficked sites unless you implement some sort of caching on the backend.

2. You can use `toDataUri()`, but this will output all the image data to the page making load times longer — potentially much longer depending on the number and size of the images you're outputting. The same warning about caching also applies.

```php
<?php
$img1 = new SimpleImage();
$img2 = new SimpleImage();
$img3 = new SimpleImage();

// Load and manipulate images here
?>

<img src="<?= $img1->toDataUri(); ?>">
<img src="<?= $img2->toDataUri(); ?>">
<img src="<?= $img3->toDataUri(); ?>">
```

3. You can generate actual files and link them as usual:

```php
<?php
$img1 = new SimpleImage();
$img2 = new SimpleImage();
$img3 = new SimpleImage();

// Load and manipulate images here

$img1->toFile('image-1.jpg');
$img2->toFile('image-2.jpg');
$img3->toFile('image-3.jpg');
?>

<img src="image-1.jpg">
<img src="image-2.jpg">
<img src="image-3.jpg">
```

For a production site, this is probably the best method since the files act as your cache and the script only needs to generate the images once, reducing the load on your server.

**Comment by mike0liveira** [comment]
Allsome, works like a charm, ty very much... used the first option:

**thumbgen.php**
```
<?php
require 'SimpleImage.php';

$image_path = $_GET["folder"]."/".$_GET["img"];

$maxw = $_GET["w"];
$maxh = $_GET["h"];

error_reporting(E_ALL & ~E_NOTICE);

	try {
		  
		  $image = new \claviska\SimpleImage();
		
		  $image
			->fromFile($image_path)
			->autoOrient()                       
			->thumbnail($maxw, $maxh, "center")
			->toScreen();
		
		} catch(Exception $err) {
		 
		  echo $err->getMessage();
	}
?>
```

**index.php**
```
<?php
$num = $site->products_index();
for($i=0;$i<$num;$i++){
?>

<img src="thumbgen.php?folder=images/products/<?php echo $site->res["folder"][$i]?>/&foto=<?php echo $site->res["img"][$i]?>&w=170&h=195"  />

<?php }?>
```
