### ISSUE TITLE
imagepalettetotruecolor not found

### ISSUE THREAD

**Issue by ArvyRogerio** [claviska/SimpleImage#225]
For some reason, my Raspberry 3 running CentOS 7 (ARM), PHP 5.6.31, with GD, returns "imagepalettetotruecolor not found" error on SimpleImage... Did I miss something?

Linux raspberry 4.9.80-v7.1.el7 #1 SMP Thu Mar 15 13:29:03 UTC 2018 armv7l armv7l armv7l GNU/Linux
PHP 5.6.31 (cli) (built: Sep 26 2017 14:03:31)
GD Version | bundled (2.1.0 compatible)

I've fixed inserting this function on simpleimage.php. Maybe can help others.

```php
if (!function_exists('imagepalettetotruecolor')) {
   function imagepalettetotruecolor(&$src) {
       if (imageistruecolor($src)) return(true);
       $dst = imagecreatetruecolor(imagesx($src), imagesy($src));
       imagecopy($dst, $src, 0, 0, 0, 0, imagesx($src), imagesy($src));
       imagedestroy($src);
       $src = $dst;
       return(true);
    }
}
```

**Comment by claviska** [comment]
I'm guessing your version of GD was compiled without support for that method. I haven't seen this happen in hosting environments, and there's nothing mentioned for that function in the PHP manual so I'm not sure.

Thanks for the shim. If anyone else is experiencing this, please comment below. If it turns out to be more than an edge case, it may be worth shimming the lib.
