### ISSUE TITLE
If Can't resolve issue why you upload this?

### ISSUE THREAD

**Issue by jilaan** [claviska/SimpleImage#232]
Hi Dear,

recently i submitted my issue but you deleted my issue why?

if you can't resolve issue then you can delete from here your script.

Thanks

**Comment by claviska** [comment]
[You posted a personal question](https://github.com/claviska/SimpleImage/issues/231) to an open source project's issue tracker. It's a place for bugs, features, etc. that relate to the project — not your free, personal support forum.

I was kind enough to throw out a suggestion in my spare time rather then tell you to get lost. However, when [I asked you](https://github.com/claviska/SimpleImage/issues/231#issuecomment-423673135) to post an actual error message [you responded](https://github.com/claviska/SimpleImage/issues/231#issuecomment-423708637) with links to blank pages. Since you didn't provide any useful troubleshooting info, I gave you my best guess as to what was happening and closed the issue to prevent clutter in the tracker.

Had you followed [my suggestion](https://github.com/claviska/SimpleImage/issues/231#issuecomment-423943358), you probably would have found a useful error message that would tell you exactly what's going on. Instead, you decided to [post a rude comment](https://github.com/claviska/SimpleImage/issues/228#issuecomment-424176259) on another issue and open this one bitching about how I'm not helping you.

So let me be clear: I owe you nothing. No open source maintainer owes you free support. We don't work for you. Even if we choose to help other people now and then, we're under zero obligation to do so for you or anyone else.

That said, if you want to post an actual error message on the [original issue](https://github.com/claviska/SimpleImage/issues/231), I'll be happy to give you some insight. But please don't act like an entitled prick. The Internet has enough of those already. ✌️

**Comment by jilaan** [comment]
O Sorry actually i am new so i don't know if this issue resolve then going on close.

now its work fine. again sorry. you can close this also.

thanks
