### ISSUE TITLE
Wrong $boundary['height'] and $boundary['y2'] for multiline text

### ISSUE THREAD

**Issue by Brullworfel** [claviska/SimpleImage#239]
If you print multiline text with $image->text(), returned $boundary['height'] and $boundary['y2'] are calculated just for first line size.

**Comment by claviska** [comment]
Is this for non-Latin characters or is the font highly styled? If so, I suspect it might be due to [the way the boundary is calculated](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L878-L889). There's some history [posted here too](https://github.com/claviska/SimpleImage/issues/165).

Can you post a minimal example, preferably with a system font, so it can be reproduced and verified?

**Comment by claviska** [comment]
Can't reproduce this. If anyone has a minimal test case, feel free to post and I'll reopen.
