### ISSUE TITLE
gif animation gone after resize

### ISSUE THREAD

**Issue by Conver** [claviska/SimpleImage#258]
Is it possible to keep gif animation after resize?

**Comment by claviska** [comment]
No, as they contain multiple images. You'd need to use [something like this](https://github.com/stil/gif-endec) to extract each image, resize them, and reassemble them.

However, it's probably more performant to use a binary such as ImageMagick, for which PHP has a module. [See this post.](https://stackoverflow.com/a/718500/567486)

I'm closing this since this is outside the scope of the library.
