### ISSUE TITLE
transparent black backround help me pls

### ISSUE THREAD

**Issue by netUstad** [claviska/SimpleImage#268]
hello claviska,
The picture I sent is transparent but its background is black why does it?
![cetalogo](https://user-images.githubusercontent.com/44398549/98508688-f65e7880-2270-11eb-89ce-93ce61a56771.png)
![cetalogo](https://user-images.githubusercontent.com/44398549/98508774-20179f80-2271-11eb-989f-99ce6aa6de35.png)

**Comment by claviska** [comment]
See: https://github.com/claviska/SimpleImage/issues/236

I'm led to believe this is an issue with GD that can't be fixed in SimpleImage. The behavior varies depending on your GD version, and for years it's been an unfortunate thing we've had to deal with. Every now and then, someone will submit a patch that fixes it for their use case, only to find it breaks transparency for others.

If someone cares to take the time to dissect this further (most likely through experimenting with GD directly), the SimpleImage community will be forever grateful. Unfortunately, it's not something I'm willing to take on right now.
