### ISSUE TITLE
$img->text() should allow a fixed height

### ISSUE THREAD

**Issue by asantos** [claviska/SimpleImage#50]
I'm having an issue where I'm trying to print several lines (paragraph that contains 3 lines).

```
$lines = array('this is a nice first line', 'Hey! This is a second line', 'Perhaps this time it will work fine.');
$num = 0;
foreach($lines as $line) {
	$img->text($line, 'arvo.ttf', 25, '#ffffff', 'top left', 25, $padding['line']*$num);
	$num++;
}
```

The idea is to have a nicely printed paragraph with lines that have a fixed height.

The issue is that since SimpleImage's text box is automatically calculated, the height varies because some letters and signs are taller than others, as a result (in this particularly example) I get a not so nice-to-see paragraph with chaotic line separations.

It would be great to have a fixed height parameter.

**Comment by claviska** [comment]
We'd have to measure each [box size](http://php.net/manual/en/function.imagettfbbox.php) and try to adjust positioning manually from there. Note that the box height will be different depending on the font, angle, sizes, and even letters being used. Complicated.

A better approach might be for the function to wrap the text inside a set boundary, but [even this]((http://stackoverflow.com/questions/20453505/wrap-lines-of-text-within-image-boundaries-using-gd)) doesn't seem like a great workaround (i.e. using number of chars instead of pixel boundaries).

Since it doesn't appear to be possible in GD (at least without a huge amount of logic), I don't think we'll be able to implement it.
