### ISSUE TITLE
Text Align Right

### ISSUE THREAD

**Issue by lemoslincoln** [claviska/SimpleImage#83]
How can i align the text?
I want right align...

**Comment by claviska** [comment]
This isn't built into the library, but it [appears possible](http://stackoverflow.com/questions/2444015/right-align-text-in-an-image-with-imagettftext-php).

**Comment by mikedidomizio** [comment]
I added the code in.  The one thing that might be confusing is the default alignment.

Example:

position: top left
default alignment: left

position: top right:
default alignment: right

Maybe there should be a default alignment for text?  If left was the default example, and you chose top right for position.  You would have to give it a right alignment otherwise it would create the text right off the image

**Comment by claviska** [comment]
I support a `default` option for alignment, which would depend on the position. If the user specifies alignment, it would obviously override it.

Only problem is this would be considered a breaking change, so I'd prefer to keep the default as-is and add it to the 3.0 roadmap :)

**Comment by claviska** [comment]
Scratch that. Totally possible since alignment is a new parameter and defaults to `null`. If you'd like to add this, let me know and I'll hold off on drafting the next release.

**Comment by claviska** [comment]
Added in #100. Please submit a new PR if you want to update the default alignment based on position.
