### ISSUE TITLE
Output new image

### ISSUE THREAD

**Issue by Aduffy** [claviska/SimpleImage#86]
Creating a new image and then outputting it directly with out saving causes an error 

	require_once 'simpleimage.php';
	try {
		$img = new abeautifulsite\SimpleImage(null, 200, 300, '#ccc');
		$img->output();
	} catch(Exception $e) {
		echo 'Error: ' . $e->getMessage();
	}

Results in error: 
Warning: getimagesize() [function.getimagesize]: Filename cannot be empty in /..../test/simpleimage.php on line 627

**Comment by nazar-pc** [comment]
[Automatic format detection](https://github.com/claviska/SimpleImage/blob/master/src/abeautifulsite/SimpleImage.php#L627) works if only you modify existing file, otherwise you should specify it manually.
[Possible values](https://github.com/claviska/SimpleImage/blob/master/src/abeautifulsite/SimpleImage.php#L614)

**Comment by Aduffy** [comment]
Dh’o!!! 

Blatintly obvious - How the hell would it know what I want to out put.. … Sorry 

_____________________________________________________________________
Alex Duffield  ~  President  ~  InControl Solutions 
p: 604-940-8878
e: alex@incontrolsolutions.com <mailto:alex@incontrolsolutions.com>
http://www.incontrolsolutions.com <http://www.incontrolsolutions.com/> 

 <> Save a tree, please do not print this e-mail unless necessary
