### ISSUE TITLE
Bolting on batch mode

### ISSUE THREAD

**Issue by paxperscientiam** [claviska/SimpleImage#97]
Hey there, claviska, as suggested, I'm working on some changes to submit to you. Next, I'll incorporate CLI arguments for transformation type(s) and arguments.

[batch demo so far](https://github.com/paxperscientiam/SimpleImage/blob/batching/example/batch.php)

**Comment by claviska** [comment]
👍

**Comment by paxperscientiam** [comment]
Hey @claviska 

I've got for you, I think, a good starting point.

https://gist.github.com/paxperscientiam/a80d7b60361c786afeba

What do you think? It should probably take a second argument for "fit_to_height".

**Comment by claviska** [comment]
What would the second argument be for?

**Comment by claviska** [comment]
What would the second argument be for?

**Comment by paxperscientiam** [comment]
For specifying the height of the thumbnails.

**Comment by claviska** [comment]
Sorry, thought you were referring to a second argument in the `fit_to_height()` method. Gotcha :)

**Comment by claviska** [comment]
It's been awhile, and I think any work on batch image processing should probably remain at the discretion of the user. One reason I think we should refrain from incorporating this in the actual library: users may not be using a local file system (could be FTP, SFTP, Amazon S3, Dropbox connector, etc.).

Closing because it's ultimately out of scope for the library itself.
